spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: login-service
          uri: lb://login-service
          predicates:
            - Path=/auth/**
        - id: user-functions
          uri: lb://user-functions
          predicates:
            - Path=/api/v1/users/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
  instance:
    preferIpAddress: true

server:
  port: 8080

jpa:
  properties:
    hibernate:
      jdbc:
        time_zone: Europe/Madrid

management:
  endpoints:
    web:
      exposure:
        include: "*"
