spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: login-service

          uri: http://login-service:8081

          predicates:
            - Path=/auth/**

        - id: user-functions

          uri: http://user-functions:8083

          predicates:
            - Path=/api/v1/users/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/

server:
  port: 8080

jpa:
  properties:
    hibernate:
      jdbc:
        time_zone: Europe/Madrid

management:
  endpoints:
    web:
      exposure:
        include: "*"
