spring:
  cloud:
    gateway:
      routes:
        - id: login-service

          # URL para despliege en local
          # uri: http://localhost:8081

          # URL para despliegue con docker-compose
          # uri: http://nlb-service.minigames.svc.cluster.local:8081

          predicates:
            - Path=/auth/**

        - id: user-functions

          # URL para despliege en local
          # uri: http://localhost:8082

          # URL para despliegue con docker-compose
          uri: http://nlb-service.minigames.svc.cluster.local:8083

          predicates:
            - Path=/api/v1/users/**

eureka:
  client:
    serviceUrl:
      defaultZone : http://discovery-server:8761/eureka/