spring:
  cloud:
    gateway:
      routes:
        - id: login-service

          # URL para despliege en local
          # uri: http://localhost:8081

          # URL para despliegue con docker-compose
          uri: lb://login-service

          predicates:
            - Path=/auth/**

        - id: user-functions

          # URL para despliege en local
          # uri: http://localhost:8082

          # URL para despliegue con docker-compose
          uri: lb://user-functions

          predicates:
            - Path=/api/v1/users/**

eureka:
  client:
    serviceUrl:
      defaultZone : http://dicovery-server:8761/eureka/