apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server
  labels:
    app: discovery-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      containers:
        - name: discovery-server
          image: aleramiirez/minigames:discovery-server-v.0.12
          ports:
            - containerPort: 8761
          env:
            - name: AUDIT_API
              value: http://discovery-server:8761
            - name: SPRING_PROFILES_ACTIVE
              value: docker
