# Automatizacion

name: Push Docker images to Hub

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn --batch-mode package

      # Build and Push Images to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:

          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images for login-service
        run: |
          cd login-service
          docker build -t aleramiirez/minigames:login-service-v.0.8 .
          docker push aleramiirez/minigames:login-service-v.0.8

      - name: Build and push Docker images for discovery-server
        run: |
          cd discovery-server
          docker build -t aleramiirez/minigames:discovery-server-v.0.8 .
          docker push aleramiirez/minigames:discovery-server-v.0.8

      - name: Build and push Docker images for audit-service
        run: |
          cd audit-service
          docker build -t aleramiirez/minigames:audit-service-v.0.8 .
          docker push aleramiirez/minigames:audit-service-v.0.8

      - name: Build and push Docker images for user-functions
        run: |
          cd user-functions
          docker build -t aleramiirez/minigames:user-functions-v.0.8 .
          docker push aleramiirez/minigames:user-functions-v.0.8

      - name: Build and push Docker images for api-gateway
        run: |
          cd api-gateway
          docker build -t aleramiirez/minigames:api-gateway-v.0.8 .
          docker push aleramiirez/minigames:api-gateway-v.0.8

      # Deploy to Kubernetes
      - name: Configure kubectl
        uses: azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f manifest/eureka-deployment.yaml -n minigames
          kubectl apply -f manifest/eureka-services.yaml -n minigames
          kubectl apply -f manifest/deployment.yaml -n minigames
          kubectl apply -f manifest/services.yaml -n minigames
